/**
 * Generates src/shared/ui/icons.generated.tsx from Phosphor's regular-weight SVGs (@phosphor-icons/core, MIT).
 * The React package ships all six weights per icon (~2 KB each); we only use regular (doc 07 §5).
 * To add an icon: add its Phosphor name to ICONS and run `npm run icons`. A unit test fails if the
 * committed file is stale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

import { format, resolveConfig } from 'prettier';

export const ICONS = [
  'arrow-clockwise',
  'arrow-left',
  'arrow-right',
  'calendar-blank',
  'calendar-plus',
  'caret-down',
  'caret-left',
  'caret-right',
  'check',
  'check-circle',
  'clock',
  'copy',
  'dots-three',
  'eye',
  'eye-slash',
  'globe-hemisphere-west',
  'info',
  'list',
  'magnifying-glass',
  'minus',
  'monitor',
  'moon',
  'plus',
  'sign-out',
  'sun',
  'video-camera',
  'warning',
  'warning-circle',
  'x',
];

export const OUTPUT = fileURLToPath(
  new URL('../src/shared/ui/icons.generated.tsx', import.meta.url),
);

const require = createRequire(import.meta.url);
const pascal = (name) => name.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());
const camel = (attr) => attr.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function toJsx(name, svg) {
  if (/<(?!\/?(svg|path|rect|circle|line|polyline|polygon)\b)/.test(svg)) {
    throw new Error(`Unsupported SVG element in ${name}`);
  }
  const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
  return inner.replace(/<(\w+)([^>]*?)\/>/g, (_, tag, attrs) => {
    const props = [...attrs.matchAll(/([\w-]+)="([^"]*)"/g)].map(
      ([, key, value]) => `${camel(key)}="${value}"`,
    );
    return `<${tag} ${props.join(' ')} />`;
  });
}

/** The generated module, formatted with the repo's Prettier config so `format:check` stays green. */
export async function renderIcons() {
  const exports = ICONS.map((name) => {
    const svg = readFileSync(
      require.resolve(`@phosphor-icons/core/assets/regular/${name}.svg`),
      'utf8',
    ).trim();
    return `export const ${pascal(name)}Icon = createIcon('${pascal(name)}Icon', <>${toJsx(name, svg)}</>);`;
  });
  const source = [
    '// Generated by scripts/generate-icons.mjs from @phosphor-icons/core (MIT). Do not edit.',
    "import { createIcon } from './icon';",
    '',
    ...exports,
    '',
  ].join('\n');
  return format(source, { ...(await resolveConfig(OUTPUT)), filepath: OUTPUT });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUTPUT, await renderIcons());
  process.stdout.write(`Generated ${ICONS.length} icons\n`);
}
